services:
  service-a:
    build:
      context: .
      dockerfile: service-a/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      service-b:
        condition: service_started
    # Run production image (built during docker-compose up --build)
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  service-b:
    build:
      context: ./service-b
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
